site_name: My Docs
site_description: 'A simple ML pipeline'
site_author: 'Gemini'

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: yes
            show_source: yes
  - mermaid2

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Data Flow: data-flow.md
  - API:
    - CLI: cli.md
    - Data: data.md
    - Evaluate: evaluate.md
    - Main: main.md
    - Model: model.md
    - Predict: predict.md
    - Preprocessing: preprocessing.md
    - Training: training.md
