site_name: My Docs
site_description: 'A simple ML pipeline'
site_author: 'Gemini'

theme:
  name: shadcn

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: yes
            show_source: yes
  - mermaid2

markdown_extensions:
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      options:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - admonition

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Data Flow: data-flow.md
  - API:
    - CLI: cli.md
    - Data: data.md
    - Evaluate: evaluate.md
    - Main: main.md
    - Model: model.md
    - Predict: predict.md
    - Preprocessing: preprocessing.md
    - Training: training.md
